spring:
  application:
    name: zuul-server
server:  
  port: ${PORT:8762}
  ssl:
    enabled: true
    key-store: classpath:zuul.jks
    key-store-password: password
    key-alias: zuul
    
security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/ 

ribbon:
  IsSecured: true
  ConnectTimeout:  10000
  ReadTimeout:  10000
  eureka:
    enabled: true
  TrustStore: classpath:zuul.jks
  TrustStorePassword : bsep123
  IsHostnameValidationRequired: false